# Generated by Django 4.2.7 on 2023-11-22 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_choices_choice_choice_alter_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default=2, help_text='Enter the choice text', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='question_choices', to='student.choice'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_choices', to='student.questions'),
        ),
    ]
