# Generated by Django 4.2.7 on 2023-11-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_choice_choice_choice_choice_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='choices',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.AddField(
            model_name='questions',
            name='choices',
            field=models.CharField(help_text='Enter the choice text', max_length=250, null=True),
        ),
    ]
